[package]
name = "ru-anime-parsers-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.104"
base64 = "0.23.1"
dotenvy = "0.15.7"
# kodik-api = "0.4.0"
# kodik-api = {path = "../kodik-api-rust"}
kodik-api = {
    git = "https://github.com/YAGOPOP/kodik-api-rust",
    # branch = "feat/get-player",
    rev = "da4b7b6d05205bd30ac0195e1e44c759be4eed01"
    # rev = "d60da0e"
}
regex = "1.13.1"
reqwest = {version = "0.13.4", features=["form"]}
scraper = "0.27.0"
serde = {version = "1.0.229", features=["derive"]}
serde_json = "1.0.151"
thiserror = "2.0.20"
tokio = {version = "1.53.1", features = ["full"]}
url = "2.5.8"

[features]
default = ["kodik-api"]
kodik-api = []

[profile.ultra]
inherits = "release"
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
strip = "symbols"
debug = false
split-debuginfo = "packed"
